#!/bin/bash

exdir="$(dirname `readlink -f "$0"`)"

source "$exdir"/VARIABLES

docker exec cloud which sudo
if [ "$?" != "0" ]; then echo "please install sudo command into cloud docker"; fi

echo "---> stopping cloud and sync"
docker stop nextcloud_client_cmd
docker stop cloud

echo "---> removing file locks"
docker exec cloud_psql su -c "psql -f /removefilelocks.sql cloud" postgres

echo "---> removing sync history"
rm -fr "$CLOUD_LOCAL_FOLDER"/._sync*

echo "---> starting cloud"
docker start cloud

echo "---> rescan CLOUD"
docker exec cloud sudo -u www-data ./occ files:scan --all --verbose

echo "---> starting cloud sync"
docker start nextcloud_client_cmd

