FROM ubuntu:resolute

ENV HOME=/root
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install nextcloud-desktop-cmd

# execute with 
# docker run searchathing/nextcloud-client-cmd:latest nextcloudcmd ARGS
