#!/bin/bash

source /root/VARIABLES

inotifywait \
	-e modify,move,create,delete,delete_self \
	-m -r /nas |
while read path action file; do

	if \
		[[ "$file" =~ .*~ ]] || \
		[[ "$file" =~ ~\$\* ]] || \
		[[ "$file" =~ \.~lock\..* ]] || \
		[[ "$file" =~ \~.*\.tmp ]] || \
		[[ "$file" =~ \.DS_Store ]] || \
		[[ "$file" =~ \.ds_store ]] || \
		[[ "$file" =~ \._.* ]] || \
		[[ "$file" =~ Thumbs\.db ]] || \
		[[ "$path" =~ .*System\ Volume\ Information.* ]] || \
		[[ "$file" =~ \..*\.sw. ]] || \
		[[ "$file" =~ \..*\..sw. ]] || \
		[[ "$path" =~ .*\.TemporaryItems ]] || \
		[[ "$path" =~ .*\.Trashes.* ]] || \
		[[ "$path" =~ .*\.DocumentRevisions-V100.* ]] || \
		[[ "$path" =~ .*\.Trash-.* ]] || \
		[[ "$path" =~ .*\.fseventd.* ]] || \
		[[ "$path" =~ .*\.apdisk.* ]] || \
		[[ "$path" =~ .*\.directory.* ]] || \
		[[ "$file" =~ .*\.part ]] || \
		[[ "$file" =~ .*\.filepart ]] || \
		[[ "$file" =~ .*\.crdownload ]] || \
		[[ "$file" =~ \.synkron\..* ]] || \
		[[ "$path" =~ .*\.sync\.ffs_db.* ]] || \
		[[ "$path" =~ .*\.symform.* ]] || \
		[[ "$path" =~ .*\.symform-store.* ]] || \
		[[ "$file" =~ \.fuse_hidden.* ]] || \
		[[ "$file" =~ .*\.unison ]] || \
		[[ "$file" =~ \.nfs.* ]] || \
		[[ "$path" =~ .*My\ Saved\ Places\..* ]] || \
		[[ "$file" =~ \._sync.* ]] || \
		[[ "$file" =~ .*\.tmp ]]; then continue; fi

	s="path [$path] ; action [$action] ; file [$file]"
	echo "$s"

	echo "$(date +%s%N) $(date) $s" > /log

done

